#!/bin/sh


SYSTEM_NAME="${1}"

## USE CERTIFICATE AUTHORITHY NAMESPACE

## CREATE CERTIFICATE, PUBLIC KEY, AND NORMALIZED PUBLIC KEY FILES
$PWD/create_test_client_cert.sh "${SYSTEM_NAME}"

## MOVE CREATED FILES TO CLIENTS DIRECTORY
mv $PWD/${SYSTEM_NAME}.* /${SYSTEM_NAME} 

